### ISSUE TITLE
Pentoo isn't booting

### ISSUE THREAD

**Issue by lugarius** [pentoo/pentoo-installer#8] opened 2015-12-13 13:20 UTC
The install is success ///only the unmount returns an error ///
Please help
I pastebin everything
I am trying to install pentoo since 3 days without break :(

**Comment by ostree** [comment] 2015-12-13 14:36
@lugarius please attach a link to pastebin here

**Comment by ostree** [comment] 2015-12-13 14:54
1) Pentoo-installer does not let me use the manual partitioning option. 
2) When attempting the auto create - the swap partition is created as a normal data partition (type 83 - should be type 82)
3) Installer does not mount the /boot partition - the mount command say it is mounted but is not (how i can say it? coz in /boot as a separate partition should be lost+found folder)
4) During installation, the grub is not installed properly

r3gards

**Comment by lugarius** [comment] 2015-12-15 06:58
ostree, I need a guide from you

**Comment by blshkv** [comment] 2016-01-13 04:30
I managed to reproduce the error.

The installer creates 3 partitions by default:
sda1 (boot)
sda2 (root)
sda3 (swap)

Currently, the grub files are getting installed into sda2 /mnt/gentoo/boot and no files on
sda1 at all.

Also, sda3 partition type is wrong. It must be marked as 82 (swap) but it is marked as 83 (Linux).

Workaround. Reboot using livecd again and run the following:

First, need to install MBR (use tab to autocomplete):
bash# grub --no-floppy
 root (hd0,0)   [must be sda1 part]
 setup(hd0)

Then, move misplaced files to the proper location (the previous step will not fix it because we are not in chroot env)
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mount /dev/sda2 /mnt/gentoo
mv -r /mnt/gentoo/boot/* /mnt/boot (not sure about the exact command)

**Comment by ZeroChaos-** [comment] 2016-01-25 03:21
make sure to update the installer before using it, it works now.

**Comment by blshkv** [comment] 2016-08-04 15:28
This problem is back with the latest RC5

**Comment by ZeroChaos-** [comment] 2016-08-13 20:32
working in git

**Closed by ZeroChaos-** 2016-08-13 20:32 UTC

**Comment by blshkv** [comment] 2016-08-13 22:19
https://github.com/pentoo/pentoo-installer/commit/1311e333e5271f73314c0bd8da74e4c6ce62cca0

**Comment by r0alt** [comment] 2017-08-13 14:17
Hello, for bootloader issues (with grub) i recomend to:
it works for me !! im so happy !! :-)

- don't insert "startx" command, keep in the terminal pentoo live
- $ sudo su
- # dhcpcd eth0     -->(you need wired connection)
- # layman -s pentoo
- # emerge --sync
- # emerge pentoo-installer
- # pentoo-installer        -->(to run the pentoo-installer program)

Then install normally, you will be able to install grub2 at bootloader section

**Comment by blshkv** [comment] 2017-08-14 00:52
@r0alt I corrected your commands and leave it to you to learn why (especially -i and -1)
